In [2]:
 # Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np

arr = np.arange(6)

print("Data type:", arr.dtype)

Data type: int64


In [4]:
# Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])

if arr.dtype == np.float64:
    print("The array data type is float64.")
else:
    print("The array data type is not float64.")

The array data type is float64.


In [6]:
# Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([1+2j, 3+4j, 5+6j])

print("Data type:", arr.dtype)

Data type: complex128


In [8]:
# Convert an existing NumPy array 'arr' of integers to float32 data type.

arr = np.array([1, 2, 3, 4, 5])

arr_float32 = arr.astype(np.float32)

print("Converted Array:", arr_float32)
print("Data type:", arr_float32.dtype)

Converted Array: [1. 2. 3. 4. 5.]
Data type: float32


In [10]:
# Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1, 2, 3, 4, 5])

arr_float32 = arr.astype(np.float32)

print("Data type:", arr_float32.dtype)

Data type: float32


In [12]:
# Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
# type

def array_attributes(arr):
   return arr.shape, arr.size, arr.dtype

arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)

Shape: (2, 3)
Size: 6
Data type: int64


In [14]:
# Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

def array_dimension(arr):
    return arr.ndim

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2], [3, 4]])

print("arr1 dimension:", array_dimension(arr1))  
print("arr2 dimension:", array_dimension(arr2)) 

arr1 dimension: 1
arr2 dimension: 2


In [16]:
# Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
# size in bytes

def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([[1, 2], [3, 4]], dtype=np.int32)

item_size, total_size = item_size_info(arr)

print("Item size (bytes):", item_size)
print("Total size (bytes):", total_size)

Item size (bytes): 4
Total size (bytes): 16


In [18]:
 # Create a function array_strides that takes a NumPy array as input and returns the strides of the array

def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

strides = array_strides(arr)

print("Strides:", strides)

Strides: (12, 4)


In [20]:
#  Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
# and strides of the array.

def shape_stride_relationship(arr): 
    return arr.shape, arr.strides

arr = np.array([[10, 20, 30], [40, 50, 60]], dtype=np.int32)
shape, strides = shape_stride_relationship(arr)

print(f"Shape: {shape}")
print(f"Strides: {strides}")

Shape: (2, 3)
Strides: (12, 4)


In [22]:
# Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
# zeros with `n` elements.

def create_zeros_array(n):
    return np.zeros(n)

zeros_array = create_zeros_array(6)
print("Zeros Array:", zeros_array)

Zeros Array: [0. 0. 0. 0. 0. 0.]


In [24]:
# Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
# NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

ones_matrix = create_ones_matrix(3, 4)
print("Ones Matrix:\n", ones_matrix)

Ones Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
# Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
# `step`.

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

range_array = generate_range_array(0, 10, 2)
print("Generated Range Array:", range_array)

Generated Range Array: [0 2 4 6 8]


In [28]:
# Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
# (inclusive).

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

linear_space_array = generate_linear_space(1.0, 5.0, 10)
print("Generated Linear Space Array:", linear_space_array)

Generated Linear Space Array: [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [30]:
#  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
# identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    return np.eye(n)

identity_matrix = create_identity_matrix(4)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
# Write a function that takes a Python list and converts it into a NumPy array

def list_to_numpy_array(py_list):
    return np.array(py_list)

python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print("NumPy Array:", numpy_array)

NumPy Array: [1 2 3 4 5]


In [34]:
#  Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
# same data

original_array = np.array([10, 20, 30, 40], dtype=np.int32)

view_array = original_array.view()

view_array[0] = 99

print("Original Array:", original_array)
print("View Array:", view_array)

Original Array: [99 20 30 40]
View Array: [99 20 30 40]


In [36]:
# Write a function that takes two NumPy arrays and concatenates them along a specified axis

def concatenate_arrays(arr1, arr2, axis=0):
    try:
        result = np.concatenate((arr1, arr2), axis=axis)
        return result
    except ValueError as e:
        print(f"Concatenation error: {e}")
        return None

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(concatenate_arrays(a, b, axis=0))
print(concatenate_arrays(a, b, axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [38]:
# Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
# concatenate`.

arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5],[6]])

result = np.concatenate((arr1, arr2), axis=1)

print("Concatenated Array:\n", result)

Concatenated Array:
 [[1 2 5]
 [3 4 6]]


In [40]:
 # Write a function that vertically stacks multiple NumPy arrays given as a list

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.array([[7, 8]])

def vertical_stack(arrays):
    return np.vstack(arrays)
    
result = vertical_stack([a, b, c])
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [42]:
# Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
# with a given step size.

def create_range_array(start, end, step):
    return np.arange(start, end + 1, step)
    
arr = create_range_array(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [44]:
# Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
# (inclusive).

def generate_equal_spaced():
    return np.linspace(0, 10, 10)
    
arr = generate_equal_spaced()
print(arr)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [46]:
# Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
# 1000 (inclusive).

def generate_log_spaced():
    return np.logspace(0, 7, 5)
    
arr = generate_log_spaced()
print(arr)

[1.00000000e+00 5.62341325e+01 3.16227766e+03 1.77827941e+05
 1.00000000e+07]


In [48]:
#  Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
# are random integers between 1 and 100.

import pandas as pd

def create_random_dataframe():
    data = np.random.randint(1, 10, size=(5, 4))  
    df = pd.DataFrame(data, columns=['A', 'B', 'C', 'D'])  
    return df
    
df = create_random_dataframe()
print(df)

   A  B  C  D
0  2  8  6  2
1  5  8  4  4
2  3  9  6  6
3  1  9  1  4
4  6  7  3  3


In [50]:
#  Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
# with zeros. Use NumPy operations within the Pandas DataFrame.

def replace_negatives_with_zero(df, *columns):
    for column in columns:
        df[column] = np.where(df[column] < 0, 0, df[column])
    return df
data = {'A': [10, -5, 20, -3, 7],'B': [1, -2, -3, 4, 5]}
df = pd.DataFrame(data)

df = replace_negatives_with_zero(df, 'A','B')
print(df)

    A  B
0  10  1
1   0  0
2  20  0
3   0  4
4   7  5


In [52]:
# Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]  
print(third_element)

30


In [54]:
 # Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[2, 2] 
print(element)

9


In [56]:
# Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])
result = arr[arr > 5]

print(result)

[ 8 10  7]


In [58]:
# Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced = arr[2:6]

print(sliced)

[3 4 5 6]


In [60]:
# Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]

print(sub_array)

[[2 3]
 [5 6]]


In [62]:
# Write a NumPy function to extract elements in specific order from a given 2D array based on indices
# provided in another array.

def extract_elements_by_indices(arr_2d, index_array):
    rows = index_array[:, 0]
    cols = index_array[:, 1]
    return arr_2d[rows, cols]
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

indices = np.array([[0, 2],  
                    [2, 1],  
                    [1, 0]]) 

result = extract_elements_by_indices(arr_2d, indices)
print(result)

[30 80 40]


In [64]:
#  Create a NumPy function that filters elements greater than a threshold from a given 1D array using
# boolean indexing.

def filter_greater_than(arr, threshold):
    return arr[arr > threshold]
arr = np.array([5, 12, 7, 3, 18, 1])
result = filter_greater_than(arr, 6)
print(result)

[12  7 18]


In [66]:
# Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
# separate arrays for each dimension.

def extract_elements_3d(arr_3d, x_indices, y_indices, z_indices):
    return arr_3d[x_indices, y_indices, z_indices]
arr_3d = np.arange(27).reshape(3, 3, 3)

x_idx = np.array([0, 2, 1])
y_idx = np.array([1, 0, 2])
z_idx = np.array([2, 1, 0])

result = extract_elements_3d(arr_3d, x_idx, y_idx, z_idx)
print(result)

[ 5 19 15]


In [68]:
#  Write a NumPy function that returns elements from an array where both two conditions are satisfied
# using boolean indexing.

def filter_with_two_conditions(arr, condition1, condition2):
    return arr[condition1(arr) & condition2(arr)]
arr = np.array([1, 5, 8, 12, 3, 7, 10])
result = filter_with_two_conditions(arr,lambda x: x > 5,lambda x: x % 2 == 0)
print(result)

[ 8 12 10]


In [70]:
# Create a NumPy function that extracts elements from a 2D array using row and column indices provided
# in separate arrays.

def extract_by_row_col_indices(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 1])

result = extract_by_row_col_indices(arr_2d, row_indices, col_indices)
print(result)

[30 40 80]


In [72]:
# Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5

print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [74]:
# Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
# corresponding element in arr1 using NumPy broadcasting.

arr1 = np.array([[2, 3, 4]])  
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]]) 

result = arr2 * arr1.T  
print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [76]:
#  Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
# NumPy broadcasting.

arr1 = np.array([[1, 2, 3, 4]])  
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])
result = arr2 + arr1.T  

print(result)

[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [78]:
#  Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
# broadcasting.

arr1 = np.array([[1], 
                 [2], 
                 [3]]) 

arr2 = np.array([[10, 20, 30]]) 
result = arr1 + arr2

print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [80]:
# Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
# broadcasting. Handle the shape incompatibility.

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  

arr2 = np.array([[10, 20],
                 [30, 40]])   
arr1_reshaped = arr1[:, np.newaxis, :]   
arr2_reshaped = arr2[:, :, np.newaxis]   
result = arr1_reshaped * arr2_reshaped  

print(result)

[[[ 10  20  30]
  [ 20  40  60]]

 [[120 150 180]
  [160 200 240]]]


In [82]:
# Calculate column wise mean for the given array:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

col_mean = np.mean(arr, axis=0)

print(col_mean)

[2.5 3.5 4.5]


In [84]:
 # Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

row_max = np.max(arr, axis=1)

print(row_max)

[3 6]


In [86]:
 # For the given array, find indices of maximum value in each column.

arr = np.array([[1, 2, 8],
                [4, 5, 6]])

col_max_indices = np.argmax(arr, axis=0)

print(col_max_indices)

[1 1 0]


In [88]:
# For the given array, apply custom function to calculate moving sum along rows.

def moving_sum_rowwise(arr, window_size=2):
    result = []
    for row in arr:
        row_sum = [np.sum(row[i:i+window_size]) for i in range(len(row) - window_size + 1)]
        result.append(row_sum)
    return np.array(result)

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

output = moving_sum_rowwise(arr, window_size=2)
print(output)

[[ 3  5]
 [ 9 11]]


In [90]:
# In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6],
                [3, 5, 7]])
all_even_cols = np.all(arr % 2 == 0, axis=0)

print(all_even_cols)

[False False False]


In [92]:
#  Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
# reshaped matrix.

def reshape_array(arr, m, n):
    if arr.size != m * n:
        raise ValueError("incompatible dimensions.")
    return arr.reshape(m, n)

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = reshape_array(original_array, 2, 3)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [94]:
# Create a function that takes a matrix as input and returns the flattened array.

def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


In [96]:
# Write a function that concatenates two given arrays along a specified axis

def concatenate_arrays(arr1, arr2, axis=0):
    try:
        return np.concatenate((arr1, arr2), axis=axis)
    except ValueError as e:
        return f"Error: {e}"

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result_axis0 = concatenate_arrays(array1, array2, axis=0)
result_axis1 = concatenate_arrays(array1, array2, axis=1)

print("Concatenated along axis 0:\n", result_axis0)
print("\nConcatenated along axis 1:\n", result_axis1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [98]:
# Create a function that splits an array into multiple sub-arrays along a specified axis.

def split_array(array, indices_or_sections, axis=0):
    try:
        return np.split(array, indices_or_sections, axis=axis)
    except ValueError as e:
        return f"Error: {e}"

original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

split_result_axis0 = split_array(original_array, 3, axis=0)
split_result_axis1 = split_array(original_array, 3, axis=1)

print("Split along axis 0 (rows):")
for sub_array in split_result_axis0:
    print(sub_array)

print("\nSplit along axis 1 (columns):")
for sub_array in split_result_axis1:
    print(sub_array)

Split along axis 0 (rows):
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along axis 1 (columns):
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [100]:
 # Write a function that inserts and then deletes elements from a given array at specified indices.

def insert_and_delete(array, insert_indices, insert_values, delete_indices):
    array_after_insert = np.insert(array, insert_indices, insert_values)
    array_after_delete = np.delete(array_after_insert, delete_indices)
    return array_after_delete

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Final array:", result)

Final array: [ 1 10  4 11  5]


In [102]:
#  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(0, 101, size=10)
arr2 = np.arange(1, 11)
result = arr1 + arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise addition result:", result)

arr1: [90 80 41 89 32 75 82 84 12 31]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise addition result: [91 82 44 93 37 81 89 92 21 41]


In [104]:
# Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise subtraction result:", result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise subtraction result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [106]:
#  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`

arr1 = np.random.randint(0, 11, size=5)

arr2 = np.arange(1, 6)

result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise multiplication result:", result)

arr1: [2 4 6 3 4]
arr2: [1 2 3 4 5]
Element-wise multiplication result: [ 2  8 18 12 20]


In [108]:
#  Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`.

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)

result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise division result:", result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Element-wise division result: [2. 2. 2. 2. 2.]


In [110]:
# Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.arange(1, 6)
arr2 = arr1[::-1]

result = arr1 ** arr2  

print("arr1:", arr1)
print("arr2:", arr2)
print("Exponentiation result (arr1 ** arr2):", result)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Exponentiation result (arr1 ** arr2): [ 1 16 27 16  5]


In [112]:
# Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

def count_substring_occurrences(arr, substring):
    return np.char.count(arr, substring).sum()

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

count = count_substring_occurrences(arr, substring)
print(f"Occurrences of '{substring}':", count)

Occurrences of 'hello': 3


In [114]:
 # Write a function that extracts uppercase characters from a NumPy array of strings.

def extract_uppercase_chars(arr):
    return np.array([''.join([char for char in s if char.isupper()]) for s in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase_chars(arr)

print("Uppercase characters:", uppercase_chars)

Uppercase characters: ['H' 'W' 'OAI' 'GPT']


In [116]:
# Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = replace_substring(arr, 'apple', 'orange')

print("Modified array:", result)

Modified array: ['orange' 'banana' 'grape' 'pineorange']


In [118]:
# Write a function that concatenates strings in a NumPy array element-wise.

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)
print("Concatenated array:", result)

Concatenated array: ['HelloOpen' 'WorldAI']


In [120]:
 # Write a function that finds the length of the longest string in a NumPy array.

def longest_string_length(arr):
    return np.vectorize(len)(arr).max()

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
max_length = longest_string_length(arr)

print("Length of the longest string:", max_length)

Length of the longest string: 9


In [122]:
# Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions.

data = np.random.randint(1, 1001, size=100)

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print(f"Standard Deviation:{std_dev:.2f}")

Mean: 490.59
Median: 483.0
Variance: 81875.0619
Standard Deviation:286.14


In [124]:
# Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
# dataset.

data = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(f"25th Percentile: {percentile_25:.2f}")
print(f"75th Percentile: {percentile_75:.2f}")

25th Percentile: 43.25
75th Percentile: 82.00


In [126]:
# Create two arrays representing two sets of variables. Compute the correlation coefficient between these
# arrays using NumPy's `corrcoef` function.

x = np.random.randint(1, 101, size=100)
y = np.random.randint(1, 101, size=100)

correlation_matrix = np.corrcoef(x, y)

correlation_coefficient = correlation_matrix[0, 1]

print("Correlation Coefficient Matrix:", correlation_matrix)
print(f"Correlation Coefficient between x and y: {correlation_coefficient:.4f}")

Correlation Coefficient Matrix: [[ 1.        -0.0179539]
 [-0.0179539  1.       ]]
Correlation Coefficient between x and y: -0.0180


In [128]:
 # Create two matrices and perform matrix multiplication using NumPy's `dot` function.

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)

print("Matrix Multiplication (A dot B):", result)

Matrix Multiplication (A dot B): [[19 22]
 [43 50]]


In [130]:
#  Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
# percentiles along with the first and third quartiles.

data = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)  
percentile_90 = np.percentile(data, 90)

q1 = np.percentile(data, 25) 
q3 = np.percentile(data, 75)  

print(f"10th Percentile: {percentile_10:.2f}")
print(f"50th Percentile (Median): {percentile_50:.2f}")
print(f"90th Percentile: {percentile_90:.2f}")
print(f"1st Quartile (Q1): {q1:.2f}")
print(f"3rd Quartile (Q3): {q3:.2f}")

10th Percentile: 60.00
50th Percentile (Median): 451.00
90th Percentile: 863.80
1st Quartile (Q1): 208.50
3rd Quartile (Q3): 735.50


In [132]:
# Create a NumPy array of integers and find the index of a specific element.

arr = np.array([10, 20, 30, 40, 50])

element = 30

index = np.where(arr == element)[0]

if index.size > 0:
    print(f"Element {element} found at index: {index[0]}")
else:
    print(f"Element {element} not found in the array.")

Element 30 found at index: 2


In [134]:
# Generate a random NumPy array and sort it in ascending order.

arr = np.random.randint(1, 101, size=10)

sorted_arr = np.sort(arr)

print("Sorted array (ascending):", sorted_arr)

Sorted array (ascending): [ 9 25 30 64 67 68 68 80 85 96]


In [136]:
# Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])

filtered = arr[arr > 20]

print("Filtered elements > 20:", filtered)

Filtered elements > 20: [25 42 30]


In [138]:
 # Filter elements which are divisible by 3 from a given NumPy array.

arr = np.array([1, 5, 8, 12, 15])

filtered = arr[arr % 3 == 0]

print("Elements divisible by 3:", filtered)

Elements divisible by 3: [12 15]


In [140]:
 # Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10, 20, 30, 40, 50])

filtered = arr[(arr >= 20) & (arr <= 40)]

print("Elements between 20 and 40 (inclusive):", filtered)

Elements between 20 and 40 (inclusive): [20 30 40]


In [153]:
# For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)

=


In [167]:
# For the given NumPy array, perform byte swapping in place using `byteswap()

arr = np.array([1, 2, 3])
arr.byteswap(inplace=True)

print(arr)
print("Byte order after swap:", arr.dtype.byteorder)

[ 72057594037927936 144115188075855872 216172782113783808]
Byte order after swap: =


In [181]:
# For the given NumPy array, swap its byte order without modifying the original array using
# `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.view(arr.dtype.newbyteorder())

print("Original array:", arr)
print("Original dtype byteorder:", arr.dtype.byteorder)
print("Swapped array:", swapped_arr)
print("Swapped dtype byteorder:", swapped_arr.dtype.byteorder)

Original array: [1 2 3]
Original dtype byteorder: =
Swapped array: [16777216 33554432 50331648]
Swapped dtype byteorder: >


In [185]:
# For the given NumPy array and swap its byte order conditionally based on system endianness using
# `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)

if np.little_endian:
    swapped_arr = arr.view(arr.dtype.newbyteorder('>')) 
else:
    swapped_arr = arr.view(arr.dtype.newbyteorder('<')) 

print("Original array:", arr)
print("Original dtype byteorder:", arr.dtype.byteorder)
print("Swapped array:", swapped_arr)
print("Swapped dtype byteorder:", swapped_arr.dtype.byteorder)

Original array: [1 2 3]
Original dtype byteorder: =
Swapped array: [16777216 33554432 50331648]
Swapped dtype byteorder: >


In [187]:
# For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
# attribute `byteorder`.

import sys

arr = np.array([1, 2, 3], dtype=np.int32)

byte_order = arr.dtype.byteorder

system_byte_order = '<' if sys.byteorder == 'little' else '>'

needs_swap = (
    (byte_order != '=') and (byte_order != '|') and (byte_order != system_byte_order)
)
print("Array byte order:", byte_order)
print("System byte order:", system_byte_order)
print("Byte swap needed:", needs_swap)

Array byte order: =
System byte order: <
Byte swap needed: False


In [189]:
# Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 999

print("Original array (arr1):", arr1)
print("Copied and modified array (copy_arr):", copy_arr)

Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Copied and modified array (copy_arr): [999   2   3   4   5   6   7   8   9  10]


In [191]:
# Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

matrix = np.random.randint(1, 101, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 999

print("Modified view_slice:\n", view_slice)
print("Original matrix after modifying the slice:\n", matrix)

Modified view_slice:
 [[999  92]
 [ 33  75]]
Original matrix after modifying the slice:
 [[999  92  53]
 [ 33  75   8]
 [ 15  21  58]]


In [193]:
# Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :]
view_b += 5  

print("Modified view_b:\n", view_b)
print("Original array_a after modifying view_b:\n", array_a)

Modified view_b:
 [[ 6  7  8]
 [ 9 10 11]]
Original array_a after modifying view_b:
 [[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]


In [195]:
# Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
# reflects changes in the original `orig_array`.

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 999

print("Reshaped view:\n", reshaped_view)
print("Original array after modifying reshaped_view:\n", orig_array)

Reshaped view:
 [[999   2]
 [  3   4]
 [  5   6]
 [  7   8]]
Original array after modifying reshaped_view:
 [[999   2   3   4]
 [  5   6   7   8]]


In [209]:
#  Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

data = np.random.randint(1, 11, size=(3, 4))

data_copy = data[data > 5]
print("\n", data_copy)
data_copy[0] = 999

print("Extracted copy (data_copy):\n", data_copy)


 [10  8  7 10  9  7  9]
Extracted copy (data_copy):
 [999   8   7  10   9   7   9]


In [213]:
# Create two matrices A and B of identical shape containing integers and perform addition and subtraction
# operations between them.

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

add_result = A + B
sub_result = A - B

print("A + B:\n", add_result)
print("A - B:\n", sub_result)

A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
A - B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [215]:
 # Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

result = np.dot(C, D)
print("Matrix multiplication result (C x D):\n", result)

Matrix multiplication result (C x D):
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [219]:
# Create a matrix `E` and find its transpose.

E = np.array([[1, 2, 3],
              [4, 5, 6]])

E_transpose = E.T  

print("Transpose of E:\n", E_transpose)

Transpose of E:
 [[1 4]
 [2 5]
 [3 6]]


In [221]:
# Generate a square matrix `F` and compute its determinant.

F = np.array([[4, 2, 1],
              [3, 5, 7],
              [1, 0, 6]])

det_F = np.linalg.det(F)

print("Determinant of F:", det_F)

Determinant of F: 93.00000000000003


In [223]:
# Create a square matrix `G` and find its inverse.

G = np.array([[4, 7, 2],
              [3, 6, 1],
              [2, 5, 3]])

G_inv = np.linalg.inv(G)

print("Inverse of G:\n", G_inv)

Inverse of G:
 [[ 1.44444444 -1.22222222 -0.55555556]
 [-0.77777778  0.88888889  0.22222222]
 [ 0.33333333 -0.66666667  0.33333333]]
